version: "3.0"
services:
  apollo-router:
    container_name: router
    image: ghcr.io/apollographql/router:v1.32.0
    depends_on:
      rover:
        condition: service_completed_successfully
    environment:
      APOLLO_TELEMETRY_DISABLED: true
    command: --dev -c /dist/config/router-override.yaml --hr --supergraph /dist/schema/supergraph.graphql
    ports:
      - 3000:4000
    volumes:
      - ./ApolloRouter/config.yml:/dist/config/router-override.yaml
      - ./supergraph.graphql:/dist/schema/supergraph.graphql

  products:
    container_name: products
    build:
      context: ./Products
      dockerfile: Docker/Dockerfile
    volumes:
      - ./Products/schema.graphql:/App/schema.graphql
    ports:
      - 3001:8080

  inventory:
    container_name: inventory
    build:
      context: ./Inventory
      dockerfile: Docker/Dockerfile
    volumes:
      - ./Inventory/schema.graphql:/App/schema.graphql
    ports:
      - 3002:8080

  rover:
    build:
      context: .
      dockerfile: Rover.Dockerfile
    depends_on:
      products:
        condition: service_started
      inventory:
        condition: service_started
    environment:
      APOLLO_ELV2_LICENSE: accept
    command: supergraph compose --config /config/supergraph.yaml --output /config/supergraph.graphql
    volumes:
      - ./supergraph.yaml:/config/supergraph.yaml
      - ./supergraph.graphql:/config/supergraph.graphql
      - ./Products/schema.graphql:/config/Products/schema.graphql
      - ./Inventory/schema.graphql:/config/Inventory/schema.graphql
