sandbox:
  enabled: true

# Sandbox uses introspection to obtain your router's schema.
supergraph:
  listen: 0.0.0.0:4000
  introspection: true

# Sandbox requires the default landing page to be disabled.
homepage:
  enabled: false

include_subgraph_errors:
  all: true

headers:
  all:
    request:
      - propagate:
          matching: .*
